#!/usr/bin/perl

$params=join(' ',@ARGV); 

system("mbgrid $params");

$fname=$params;
$fname=~s/.*-O\s*//;
$fname=~s/\s+.*$//;
$fname="$fname.asc";

open IN, "$fname";
open OUT, ">temp";

$line=<IN>;
print OUT $line;
$line=<IN>;
print OUT $line;
$line=<IN>;
print OUT $line;
chomp($line);
($nx,$ny)=split /\s+/, $line; 
$line=<IN>;
print OUT $line;
chomp($line); 
($xmin,$xmax,$ymin,$ymax)=split /\s+/, $line;
for($ii=0;$ii<$nx;$ii++){
	$xc[$ii]=$xmin+($xmax-$xmin)*$ii/($nx-1);
}
for($ii=0;$ii<$ny;$ii++){
	$yc[$ii]=$ymin+($ymax-$ymin)*$ii/($ny-1);
}
$xci=0;
$yci=0;
while($line=<IN>){
	chomp $line;
	$line=~s/^\s+//;
	@nums=split /\s+/, $line;
	$len=@nums;
	for($i=0;$i<$len;$i++){
		printf OUT "%15.8e %15.8e %15.8e\n", $xc[$xci],$yc[$yci],$nums[$i];
		$yci++;
		if($yci>$ny-1){
			$yci=0;
			$xci++;
		}
	}	
}
close OUT;
close IN;
system("mv temp $fname");
